baseURL = 'https://cederberg.xyz'
languageCode = 'en-us'
title = 'cederberg'
theme = 'cederberg'

[params]
subtitle = 'under construction'

[menu]
  [[menu.main]]
    name = 'home'
    url = '/'
    weight = -100
  [[menu.main]]
    name = 'oscar'
    url = 'https://oscar.cederberg.xyz'
    weight = -95
  [[menu.main]]
    name = 'about'
    url = '/about/'
    weight = -90